## Basic Configuration

baseurl = "/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Lihao Zhang"
title = "Lihao (Jasper) Zhang"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Site Settings
[params]
author = "Lihao (Jasper) Zhang"
intro = "Data Scientist, Traveler, Amateur Billiards and Table-tennis Player"
description = "Currently Data Scientist @PwC SDC Shanghai. Previously a Longhorn [@University of Texas at Austin](https://www.utexas.edu/), Hook 'em!"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "jasper7zlh"
#instagram = "<username>"
#xing = "<username>"
linkedin = "lihao-zhang"
#twitter = "Jasperzlh"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
email = "jasperlihaozhang@gmail.com"

## Extras
[params.extra]
copyright = "© 2018-2019. Lihao Zhang. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    weight = 100
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
[[menu.main]]
    name = "miscellaneous"
    identifier = "miscellaneous"
    weight = 400
    url = "/miscellaneous/"
